//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoCurrency
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Customer_Id { get; set; }
        public int Supplier_Id { get; set; }
        public int Product_Id { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int Reserved_current { get; set; }
        public int Reserved_total { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> Type { get; set; }
        public Nullable<int> Invoice_number { get; set; }
        public Nullable<short> Warranty { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> CryptoAmount { get; set; }
    }
}
